import streamlit as st
import time
from io import BytesIO
from datetime import date, datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch

# --- Configuration & State ---
st.set_page_config(page_title="VoiceForm AI (Python)", page_icon="📝", layout="centered")

# Initialize Session State for Navigation
if 'view' not in st.session_state:
    st.session_state.view = 'home'
if 'active_form_id' not in st.session_state:
    st.session_state.active_form_id = None
if 'form_data' not in st.session_state:
    st.session_state.form_data = {}

# --- Mock Database of Forms ---
FORM_TEMPLATES = {
    'aadhar': {
        'id': 'aadhar_v1',
        'title': 'Aadhar Enrollment Form',
        'organization': 'Unique Identification Authority of India',
        'required_docs': ["Passport", "Voter ID", "Birth Certificate"],
        'fields': [
            {'id': 'full_name', 'label': 'Full Name', 'type': 'text'},
            {'id': 'dob', 'label': 'Date of Birth', 'type': 'date'},
            {'id': 'gender', 'label': 'Gender', 'type': 'select', 'options': ['Male', 'Female', 'Other']},
            {'id': 'address', 'label': 'Address', 'type': 'text_area'},
            {'id': 'mobile', 'label': 'Mobile Number', 'type': 'text'},
        ]
    },
    'generic_bank': {
        'id': 'bank_v1',
        'title': 'Account Opening Form',
        'organization': 'State Bank of General Finance',
        'required_docs': ["PAN Card", "Aadhar Card", "Driving License"],
        'fields': [
            {'id': 'app_name', 'label': 'Applicant Name', 'type': 'text'},
            {'id': 'pan', 'label': 'PAN Number', 'type': 'text'},
            {'id': 'income', 'label': 'Annual Income', 'type': 'number'},
            {'id': 'nominee', 'label': 'Nominee Name', 'type': 'text'},
        ]
    }
}

# --- Backend Logic: PDF Generation ---
def generate_pdf(form_template, form_data):
    """Generates a PDF file in memory using ReportLab."""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setStrokeColor(colors.black)
    c.setLineWidth(2)
    c.line(50, height - 50, width - 50, height - 50)
    
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 80, form_template['organization'].upper())
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.darkgrey)
    c.drawCentredString(width / 2, height - 100, form_template['title'])

    # Fields
    y_position = height - 150
    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)

    for field in form_template['fields']:
        label = field['label']
        value = str(form_data.get(field['id'], ''))
        
        # Draw Label
        c.setFont("Helvetica-Bold", 10)
        c.drawString(72, y_position, label.upper())
        
        # Draw Value or Placeholder
        c.setFont("Courier", 12)
        if value:
            c.drawString(72, y_position - 15, value)
        else:
            c.setFillColor(colors.lightgrey)
            c.drawString(72, y_position - 15, "[Empty]")
            c.setFillColor(colors.black)
            
        # Draw Line
        c.setLineWidth(0.5)
        c.line(72, y_position - 20, width - 72, y_position - 20)
        
        y_position -= 50

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(72, 50, f"Generated by VoiceForm AI (Python) | Date: {date.today()}")
    
    c.save()
    buffer.seek(0)
    return buffer

# --- Mock OCR Logic for ID Cards ---
def extract_data_from_id(image_file):
    """
    Simulates OCR extraction from an uploaded ID card.
    """
    time.sleep(1.5) # Simulate processing delay
    
    # Mock extracted data
    extracted = {
        'full_name': "Rahul Sharma",
        'app_name': "Rahul Sharma",
        'dob': date(1995, 8, 15),
        'address': "H.No 42, MG Road, Indiranagar, Bengaluru, 560038",
        'gender': "Male",
        'mobile': "9876543210",
        'pan': "ABCDE1234F",
        'nominee': "Priya Sharma"
    }
    return extracted

# --- UI Functions ---

def render_home():
    st.title("📝 VoiceForm AI")
    st.write("Digitize physical forms, verify templates, and generate PDFs.")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.info("📷 Scan Document")
        if st.button("Start Camera Scan", use_container_width=True):
            st.session_state.scan_type = 'camera'
            st.session_state.view = 'scanning'
            st.rerun()

    with col2:
        st.info("📟 Scan Barcode")
        if st.button("Start QR Scan", use_container_width=True):
            st.session_state.scan_type = 'barcode'
            st.session_state.view = 'scanning'
            st.rerun()

def render_scanning():
    st.title("Scanning...")
    progress_bar = st.progress(0)
    status_text = st.empty()
    
    scan_type = st.session_state.get('scan_type', 'camera')
    
    stages = [
        (10, "Initializing sensor..."),
        (30, "Locating document edges..."),
        (60, "Processing image data..."),
        (100, "Complete!")
    ]
    
    for percent, text in stages:
        time.sleep(0.3)
        progress_bar.progress(percent)
        status_text.text(text)
    
    found_id = 'aadhar' if scan_type == 'barcode' else 'generic_bank'
    st.session_state.active_form_id = found_id
    st.session_state.view = 'verification'
    st.rerun()

def render_verification():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    
    st.title("🔍 Verify Form")
    st.write("Is this the correct document template?")
    
    with st.container():
        st.markdown(f"""
        <div style="background-color: #f0f2f6; padding: 20px; border-radius: 10px; border: 1px solid #ccc;">
            <h3 style="color: #333; margin: 0;">{template['title']}</h3>
            <p style="color: #666; font-size: 0.9em;">{template['organization']}</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.write("")
    col1, col2 = st.columns(2)
    with col1:
        if st.button("❌ Rescan"):
            st.session_state.view = 'home'
            st.rerun()
    with col2:
        if st.button("✅ Yes, Proceed"):
            st.session_state.view = 'choice_mode'
            st.session_state.form_data = {} 
            st.rerun()

# --- New Feature: Choice Mode ---
def render_choice_mode():
    st.title("Choose Input Method")
    st.write("How would you like to fill this form?")
    
    st.write("")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.image("https://cdn-icons-png.flaticon.com/512/337/337946.png", width=80)
        st.subheader("Upload Docs")
        st.caption("Auto-fill by uploading relevant docs.")
        if st.button("📂 Upload Document", use_container_width=True):
            st.session_state.view = 'upload_process'
            st.rerun()
            
    with col2:
        st.image("https://cdn-icons-png.flaticon.com/512/2983/2983802.png", width=80)
        st.subheader("Dictate / Fill")
        st.caption("Use voice or text to fill manually.")
        if st.button("🗣️ Dictate Info", use_container_width=True):
            st.session_state.view = 'filling'
            st.rerun()

# --- New Feature: Dedicated Upload Process ---
def render_upload_process():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    req_docs = ", ".join(template.get('required_docs', ["Government ID"]))

    st.title("📂 Upload Required Document")
    st.markdown(f"To auto-fill the **{template['title']}**, please upload a valid proof containing the required details.")
    
    st.info(f"**Accepted Documents:** {req_docs}")
    
    uploaded_file = st.file_uploader(f"Upload one of the following: {req_docs}", type=['jpg', 'png', 'jpeg'])
    
    col1, col2 = st.columns([1, 4])
    with col1:
        if st.button("⬅️ Back"):
            st.session_state.view = 'choice_mode'
            st.rerun()
            
    if uploaded_file is not None:
        if st.button("🚀 Extract & Continue", type="primary"):
            with st.spinner("Analyzing document..."):
                extracted_data = extract_data_from_id(uploaded_file)
                
                # Merge data
                form_field_ids = [f['id'] for f in template['fields']]
                
                count = 0
                for key, value in extracted_data.items():
                    if key in form_field_ids:
                        st.session_state.form_data[key] = value
                        count += 1
                
                st.success(f"Extracted {count} fields successfully!")
                time.sleep(1)
                st.session_state.view = 'filling'
                st.rerun()

def render_filling():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    
    st.title(f"✍️ {template['title']}")
    
    with st.form("filling_form"):
        st.caption("Review extracted data or enter details below.")
        
        new_data = {}
        for field in template['fields']:
            label = field['label']
            fid = field['id']
            
            # Use data from session state (populated by Upload OR empty)
            default_val = st.session_state.form_data.get(fid)
            
            if field['type'] == 'text':
                new_data[fid] = st.text_input(label, value=default_val if default_val else "")
            elif field['type'] == 'number':
                val = default_val if default_val is not None else 0
                new_data[fid] = st.number_input(label, value=int(val), step=1)
            elif field['type'] == 'date':
                val = default_val if default_val else None
                new_data[fid] = st.date_input(label, value=val)
            elif field['type'] == 'select':
                options = field['options']
                index = 0
                if default_val in options:
                    index = options.index(default_val)
                new_data[fid] = st.selectbox(label, options, index=index)
            elif field['type'] == 'text_area':
                new_data[fid] = st.text_area(label, value=default_val if default_val else "")
        
        submitted = st.form_submit_button("Preview & Download")
        if submitted:
            st.session_state.form_data = new_data
            st.session_state.view = 'preview'
            st.rerun()

def render_preview():
    st.title("📄 Document Preview")
    
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    data = st.session_state.form_data
    
    pdf_file = generate_pdf(template, data)
    
    st.markdown("### Data Summary")
    for field in template['fields']:
        val = data.get(field['id'], '-')
        st.text(f"{field['label']}: {val}")
        
    st.success("Document generated successfully!")
    
    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="⬇️ Download PDF",
            data=pdf_file,
            file_name=f"{form_id}_filled.pdf",
            mime="application/pdf",
        )
    with col2:
        if st.button("🏠 Start New Scan"):
            st.session_state.view = 'home'
            st.rerun()

# --- Main App Controller ---
def main():
    if st.session_state.view == 'home':
        render_home()
    elif st.session_state.view == 'scanning':
        render_scanning()
    elif st.session_state.view == 'verification':
        render_verification()
    elif st.session_state.view == 'choice_mode':
        render_choice_mode()
    elif st.session_state.view == 'upload_process':
        render_upload_process()
    elif st.session_state.view == 'filling':
        render_filling()
    elif st.session_state.view == 'preview':
        render_preview()

if __name__ == "__main__":
    main()