import streamlit as st
import time
from io import BytesIO
from datetime import date, datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch

# --- Voice & Audio Imports ---
try:
    from streamlit_mic_recorder import mic_recorder
    import speech_recognition as sr
    VOICE_AVAILABLE = True
except ImportError:
    VOICE_AVAILABLE = False

# --- Configuration & State ---
st.set_page_config(page_title="Sahayam", page_icon="📝", layout="centered")

# Initialize Session State
if 'view' not in st.session_state:
    st.session_state.view = 'home'
if 'active_form_id' not in st.session_state:
    st.session_state.active_form_id = None
if 'form_data' not in st.session_state:
    st.session_state.form_data = {}

# --- Mock Database of Forms ---
FORM_TEMPLATES = {
    'aadhar': {
        'id': 'aadhar_v1',
        'title': 'Aadhar Enrollment Form',
        'organization': 'Unique Identification Authority of India',
        'required_docs': ["Passport", "Voter ID", "Birth Certificate"],
        'fields': [
            {'id': 'full_name', 'label': 'Full Name', 'type': 'text'},
            {'id': 'dob', 'label': 'Date of Birth', 'type': 'date'},
            {'id': 'gender', 'label': 'Gender', 'type': 'select', 'options': ['Male', 'Female', 'Other']},
            {'id': 'address', 'label': 'Address', 'type': 'text_area'},
            {'id': 'mobile', 'label': 'Mobile Number', 'type': 'text'},
        ]
    },
    'generic_bank': {
        'id': 'bank_v1',
        'title': 'Account Opening Form',
        'organization': 'State Bank of General Finance',
        'required_docs': ["PAN Card", "Aadhar Card", "Driving License"],
        'fields': [
            {'id': 'app_name', 'label': 'Applicant Name', 'type': 'text'},
            {'id': 'pan', 'label': 'PAN Number', 'type': 'text'},
            {'id': 'income', 'label': 'Annual Income', 'type': 'number'},
            {'id': 'nominee', 'label': 'Nominee Name', 'type': 'text'},
        ]
    }
}

# --- Backend Logic: PDF Generation ---
def generate_pdf(form_template, form_data):
    """Generates a PDF file in memory using ReportLab."""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setStrokeColor(colors.black)
    c.setLineWidth(2)
    c.line(50, height - 50, width - 50, height - 50)
    
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 80, form_template['organization'].upper())
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.darkgrey)
    c.drawCentredString(width / 2, height - 100, form_template['title'])

    # Fields
    y_position = height - 150
    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)

    for field in form_template['fields']:
        label = field['label']
        value = str(form_data.get(field['id'], ''))
        
        # Draw Label
        c.setFont("Helvetica-Bold", 10)
        c.drawString(72, y_position, label.upper())
        
        # Draw Value or Placeholder
        c.setFont("Courier", 12)
        if value:
            c.drawString(72, y_position - 15, value)
        else:
            c.setFillColor(colors.lightgrey)
            c.drawString(72, y_position - 15, "[Empty]")
            c.setFillColor(colors.black)
            
        # Draw Line
        c.setLineWidth(0.5)
        c.line(72, y_position - 20, width - 72, y_position - 20)
        
        y_position -= 50

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(72, 50, f"Generated by Sahayam | Date: {date.today()}")
    
    c.save()
    buffer.seek(0)
    return buffer

# --- Mock OCR Logic ---
def extract_data_from_id(image_file):
    time.sleep(1.5)
    extracted = {
        'full_name': "Rahul Sharma",
        'app_name': "Rahul Sharma",
        'dob': date(1995, 8, 15),
        'address': "H.No 42, MG Road, Indiranagar, Bengaluru, 560038",
        'gender': "Male",
        'mobile': "9876543210",
        'pan': "ABCDE1234F",
        'nominee': "Priya Sharma"
    }
    return extracted

# --- Voice Processing Logic ---
def process_audio(audio_bytes):
    """
    Convert audio bytes to text using SpeechRecognition
    """
    r = sr.Recognizer()
    # Convert bytes to file-like object
    audio_file = BytesIO(audio_bytes)
    
    try:
        with sr.AudioFile(audio_file) as source:
            audio_data = r.record(source)
            # Use Google Web Speech API (Free, no key required for basic use)
            text = r.recognize_google(audio_data)
            return text
    except sr.UnknownValueError:
        return "Could not understand audio"
    except sr.RequestError as e:
        return f"Could not request results; {e}"
    except Exception as e:
        return f"Error: {e}"

# --- UI Functions ---

def render_home():
    st.title("📝 Sahayam")
    st.write("Digitize physical forms, verify templates, and generate PDFs.")
    
    col1, col2 = st.columns(2)
    with col1:
        st.info("📷 Scan Document")
        if st.button("Start Camera Scan", use_container_width=True):
            st.session_state.scan_type = 'camera'
            st.session_state.view = 'scanning'
            st.rerun()
    with col2:
        st.info("📟 Scan Barcode")
        if st.button("Start QR Scan", use_container_width=True):
            st.session_state.scan_type = 'barcode'
            st.session_state.view = 'scanning'
            st.rerun()

    if not VOICE_AVAILABLE:
        st.warning("⚠️ Voice features disabled. Please install libraries: `pip install streamlit-mic-recorder SpeechRecognition`")

def render_scanning():
    st.title("Scanning...")
    progress_bar = st.progress(0)
    status_text = st.empty()
    scan_type = st.session_state.get('scan_type', 'camera')
    
    stages = [(10, "Initializing sensor..."), (50, "Processing..."), (100, "Complete!")]
    for percent, text in stages:
        time.sleep(0.3)
        progress_bar.progress(percent)
        status_text.text(text)
    
    found_id = 'aadhar' if scan_type == 'barcode' else 'generic_bank'
    st.session_state.active_form_id = found_id
    st.session_state.view = 'verification'
    st.rerun()

def render_verification():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    
    st.title("🔍 Verify Form")
    with st.container():
        st.markdown(f"""
        <div style="background-color: #f0f2f6; padding: 20px; border-radius: 10px; border: 1px solid #ccc;">
            <h3 style="color: #333; margin: 0;">{template['title']}</h3>
            <p style="color: #666; font-size: 0.9em;">{template['organization']}</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.write("")
    col1, col2 = st.columns(2)
    with col1:
        if st.button("❌ Rescan"):
            st.session_state.view = 'home'
            st.rerun()
    with col2:
        if st.button("✅ Yes, Proceed"):
            st.session_state.view = 'choice_mode'
            st.session_state.form_data = {} 
            st.rerun()

def render_choice_mode():
    st.title("Choose Input Method")
    col1, col2 = st.columns(2)
    
    with col1:
        st.image("https://cdn-icons-png.flaticon.com/512/337/337946.png", width=80)
        st.subheader("Upload Docs")
        if st.button("📂 Upload Document", use_container_width=True):
            st.session_state.view = 'upload_process'
            st.rerun()
            
    with col2:
        st.image("https://cdn-icons-png.flaticon.com/512/2983/2983802.png", width=80)
        st.subheader("Dictate / Fill")
        if st.button("🗣️ Dictate Info", use_container_width=True):
            st.session_state.view = 'filling'
            st.rerun()

def render_upload_process():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    req_docs = ", ".join(template.get('required_docs', ["Government ID"]))

    st.title("📂 Upload Document")
    st.info(f"Please upload: {req_docs}")
    
    uploaded_file = st.file_uploader("Upload Image", type=['jpg', 'png', 'jpeg'])
    
    col1, col2 = st.columns([1, 4])
    with col1:
        if st.button("⬅️ Back"):
            st.session_state.view = 'choice_mode'
            st.rerun()
            
    if uploaded_file is not None:
        if st.button("🚀 Extract Data", type="primary"):
            with st.spinner("Analyzing..."):
                extracted_data = extract_data_from_id(uploaded_file)
                form_field_ids = [f['id'] for f in template['fields']]
                for key, value in extracted_data.items():
                    if key in form_field_ids:
                        st.session_state.form_data[key] = value
                st.session_state.view = 'filling'
                st.rerun()

def render_filling():
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    
    st.title(f"✍️ {template['title']}")

    # --- ACTUAl VOICE TO TEXT SECTION ---
    if VOICE_AVAILABLE:
        with st.expander("🎙️ Voice Dictation (Beta)", expanded=True):
            st.write("Select a field, record your answer, and it will be filled below.")
            
            # 1. Select Target Field
            # Create a map of Label -> ID for the dropdown
            field_map = {f['label']: f['id'] for f in template['fields']}
            target_label = st.selectbox("Which field are you speaking for?", options=list(field_map.keys()))
            target_id = field_map[target_label]

            # 2. Record Audio
            col_mic, col_status = st.columns([1, 3])
            with col_mic:
                # Returns dictionary {'bytes': b'...', 'sample_rate': 44100}
                audio = mic_recorder(
                    start_prompt="🎤 Record",
                    stop_prompt="🛑 Stop",
                    key='recorder',
                    format='wav' # Request WAV format for SpeechRecognition
                )
            
            with col_status:
                if audio:
                    with st.spinner("Transcribing voice..."):
                        # 3. Transcribe
                        text_output = process_audio(audio['bytes'])
                        
                        # Update session state with transcribed text
                        st.session_state.form_data[target_id] = text_output
                        st.success(f"Recognized: '{text_output}'")
                else:
                    st.write("Press Record to speak.")

    # --- Form Rendering ---
    with st.form("filling_form"):
        st.markdown("---")
        
        new_data = {}
        for field in template['fields']:
            label = field['label']
            fid = field['id']
            
            # Data flows from: Upload Extraction OR Voice Dictation OR Manual Input
            default_val = st.session_state.form_data.get(fid)
            
            if field['type'] == 'text':
                new_data[fid] = st.text_input(label, value=default_val if default_val else "")
            elif field['type'] == 'number':
                val = default_val if default_val is not None and str(default_val).isdigit() else 0
                new_data[fid] = st.number_input(label, value=int(val), step=1)
            elif field['type'] == 'date':
                val = default_val if default_val and isinstance(default_val, date) else None
                new_data[fid] = st.date_input(label, value=val)
            elif field['type'] == 'select':
                options = field['options']
                index = 0
                if default_val in options:
                    index = options.index(default_val)
                new_data[fid] = st.selectbox(label, options, index=index)
            elif field['type'] == 'text_area':
                new_data[fid] = st.text_area(label, value=default_val if default_val else "")
        
        submitted = st.form_submit_button("Preview & Download")
        if submitted:
            st.session_state.form_data = new_data
            st.session_state.view = 'preview'
            st.rerun()

def render_preview():
    st.title("📄 Document Preview")
    
    form_id = st.session_state.active_form_id
    template = FORM_TEMPLATES[form_id]
    data = st.session_state.form_data
    
    pdf_file = generate_pdf(template, data)
    
    st.markdown("### Data Summary")
    for field in template['fields']:
        val = data.get(field['id'], '-')
        st.text(f"{field['label']}: {val}")
        
    col1, col2 = st.columns(2)
    with col1:
        st.download_button("⬇️ Download PDF", pdf_file, f"{form_id}_filled.pdf", "application/pdf")
    with col2:
        if st.button("🏠 Start New Scan"):
            st.session_state.view = 'home'
            st.rerun()

# --- Main App Controller ---
def main():
    if st.session_state.view == 'home': render_home()
    elif st.session_state.view == 'scanning': render_scanning()
    elif st.session_state.view == 'verification': render_verification()
    elif st.session_state.view == 'choice_mode': render_choice_mode()
    elif st.session_state.view == 'upload_process': render_upload_process()
    elif st.session_state.view == 'filling': render_filling()
    elif st.session_state.view == 'preview': render_preview()

if __name__ == "__main__":
    main()
